// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repo

import (
	"database/sql"
)

type Accesstoken struct {
	ID             int64
	ExpirationTime int64
	Token          sql.NullString
	UserID         int64
}

type Emailactivationcode struct {
	ID             int64
	ActivationCode int64
	ExpirationTime int64
	UserID         int64
}

type User struct {
	ID             int64
	FirstName      string
	LastName       string
	Email          string
	EmailActivated interface{}
	EncrPassword   sql.NullString
	SaltPassword   sql.NullString
	TempPassword   sql.NullString
	IsDeleted      interface{}
}
